/**
 * FIX-914 — generate the `derive_nh_floterials()` migration from the proven
 * exact-cover fixture.
 *
 *   pnpm --filter @civitics/data data:nh:migration            # write the SQL
 *   pnpm --filter @civitics/data data:nh:migration -- --check # diff only
 *
 * The 39 rows the migration seeds are NOT typed by hand: they come out of
 * `nh-floterials-2022.derived.json`, which comes out of the exact-cover proof in
 * `nh-house-districts-2022.test.ts`, which comes out of the checked-in RSA 662:5
 * HTML. `fix914-migration-matches-fixture.test.ts` asserts the committed SQL is
 * exactly what this script emits, so the JSON, the fixture and the SQL cannot
 * drift apart.
 *
 * Both the emitted spec and the surrounding function body live here so the
 * migration stays a single reviewable artifact — a reader of
 * supabase/migrations/ sees the whole derivation, not a call into a script.
 */

import * as fs from "fs";
import * as path from "path";

export interface FloterialSpec {
  district_id: string;
  county: string;
  number: number;
  seats: number;
  name: string;
  base_district_ids: string[];
}

const DERIVED_PATH = path.join(__dirname, "..", "data", "nh-floterials-2022.derived.json");
export const MIGRATION_PATH = path.join(
  __dirname, "..", "..", "..", "..",
  "supabase", "migrations", "20260910120000_fix914_nh_floterial_districts.sql",
);

export function readSpec(): FloterialSpec[] {
  const f = JSON.parse(fs.readFileSync(DERIVED_PATH, "utf8")) as { floterials: FloterialSpec[] };
  return f.floterials;
}

/** The spec as the JSONB literal the function carries, one district per line. */
export function specLiteral(rows: FloterialSpec[]): string {
  return rows.map((r) => `  ${JSON.stringify({
    district_id: r.district_id,
    county: r.county,
    number: r.number,
    seats: r.seats,
    name: r.name,
    base_district_ids: r.base_district_ids,
  })}`).join(",\n");
}

export function buildMigration(rows: FloterialSpec[]): string {
  const seats = rows.reduce((n, r) => n + r.seats, 0);
  return `-- FIX-914 — the 39 New Hampshire floterial House districts, derived as unions
-- of the TIGER base districts they span.
--
-- New Hampshire elects 400 representatives from 203 districts. 164 of those are
-- ordinary base districts and arrive as TIGER SLDL features; the other 39 are
-- FLOTERIAL districts — an overlay district spanning several WHOLE base
-- districts and electing its own representatives on top of theirs. A floterial
-- is not a Census geography, so TIGER publishes none of them, and the ${seats}
-- representatives elected from them had no jurisdictions row to link to. That is
-- the permanent residual FIX-913 and FIX-859 documented and declined to guess at.
--
-- The membership is statutory (RSA 662:5, the 2022 plan) and is checked in at
-- packages/data/src/data/nh-house-districts-2022.json together with the proof
-- that every floterial is an EXACT union of whole base districts — no town
-- missing, none extra, no base district split. The base_district_ids below come
-- out of that proof (nh-floterials-2022.derived.json); this file is GENERATED by
-- packages/data/src/scripts/gen-fix914-migration.ts and a test asserts the two
-- agree, so the SQL cannot drift from the statute.
--
-- AFTER THIS, NEW HAMPSHIRE'S 'HD' ROWS NO LONGER PARTITION THE STATE. 39
-- polygons overlap the 164, and that is correct: a Belmont resident really is
-- represented by both Belknap 4 and Belknap 8. Readers that assumed "one
-- district contains this point" are handled in the same set as this migration;
-- see the FIX-914 reader sweep.
--
-- link_officials_to_districts() is NOT touched. Its FIX-913 body keys on
-- type='district' + an 'HD'/'SD' short_name prefix + the parent state, and
-- matches at tier 3 on the normalised core — 'Belknap 8' and 'New Hampshire
-- State House District Belknap 08' both reduce to 'belknap-08'. So a derived row
-- named in the TIGER pattern links with no RPC change and with an honest
-- metadata.source of 'derived' rather than a mislabelled 'tiger'.

-- ── Idempotency, pinned in the schema rather than in a script's memory ───────
--
-- The floterial rows carry census_geoid = NULL on purpose: a floterial is not a
-- Census geography and a fabricated '33008' would be a lie. That puts them
-- OUTSIDE jurisdictions_district_geoid_chamber_unique (which is partial on
-- census_geoid IS NOT NULL), so the derived set needs a uniqueness key of its
-- own. Without it a re-run after a TIGER refresh would mint a second Belknap 8.
CREATE UNIQUE INDEX IF NOT EXISTS jurisdictions_derived_district_unique
  ON public.jurisdictions (parent_id, (metadata->>'chamber'), (metadata->>'district_id'))
  WHERE type = 'district' AND metadata->>'source' = 'derived';

-- ── The derivation ──────────────────────────────────────────────────────────
--
-- Exposed as a function, not inlined, because the TIGER ingest calls it after
-- writing New Hampshire's lower chamber: a tiger_year bump rewrites the base
-- geometries, and the floterials must be re-unioned from the new ones or they
-- silently keep the old shape. Through the unique index above that re-union is
-- an UPDATE in place, never a second row.
--
-- statement_timeout is pinned because the pipelines call this as service_role,
-- whose prod default is 8s. 39 unions over 2-6 polygons we already hold runs in
-- seconds, but the same convention as link_officials_to_districts() applies:
-- do not leave a pipeline one slow plan away from a timeout.
CREATE OR REPLACE FUNCTION public.derive_nh_floterials()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
SET statement_timeout = '5min'
AS $fn$
DECLARE
  -- Generated from nh-floterials-2022.derived.json. district_id is the TIGER
  -- SLDLST form (county index + zero-padded number: Belknap 8 -> '008',
  -- Hillsborough 37 -> '537'); base_district_ids are the TIGER district_ids of
  -- the base districts the floterial spans -- portable across environments,
  -- never uuids.
  v_spec CONSTANT jsonb := $spec$[
${specLiteral(rows)}
]$spec$::jsonb;
  v_parent  uuid;
  v_missing text;
  v_count   integer;
BEGIN
  SELECT id INTO v_parent
    FROM public.jurisdictions
   WHERE type = 'state' AND fips_code = '33';
  IF v_parent IS NULL THEN
    RAISE EXCEPTION 'derive_nh_floterials: no New Hampshire state jurisdiction (type=state, fips_code=33)';
  END IF;

  -- NEVER INSERT A PARTIAL UNION. A floterial that resolves fewer base rows
  -- than its list names would still produce a valid polygon -- a smaller, wrong
  -- one -- and nothing downstream would notice. Refuse the whole run instead.
  SELECT string_agg(
           format('%s (wanted %s, resolved %s)',
                  s.district_id, array_length(s.base_district_ids, 1), s.n),
           ', ' ORDER BY s.district_id)
    INTO v_missing
    FROM (
      SELECT x.district_id,
             x.base_district_ids,
             count(b.id) AS n
        FROM jsonb_to_recordset(v_spec)
               AS x(district_id text, county text, number int, seats int,
                    name text, base_district_ids text[])
        LEFT JOIN public.jurisdictions b
               ON b.parent_id = v_parent
              AND b.type = 'district'
              AND b.short_name LIKE 'HD %'
              AND b.metadata->>'chamber' = 'lower'
              AND b.metadata->>'source' = 'tiger'
              AND b.boundary_geometry IS NOT NULL
              AND b.metadata->>'district_id' = ANY (x.base_district_ids)
       GROUP BY x.district_id, x.base_district_ids
    ) s
   WHERE s.n <> array_length(s.base_district_ids, 1);

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'derive_nh_floterials: base districts missing for %', v_missing;
  END IF;

  WITH spec AS (
    SELECT * FROM jsonb_to_recordset(v_spec)
      AS x(district_id text, county text, number int, seats int,
           name text, base_district_ids text[])
  ),
  unioned AS (
    SELECT s.district_id,
           s.name,
           s.seats,
           s.base_district_ids,
           -- tiger_year and legislative_session_year are read OFF the base rows
           -- rather than frozen into this migration: after a TIGER bump the
           -- re-union must describe the geometry it actually used, not the
           -- vintage that happened to be current the day this was written.
           min(b.metadata->>'tiger_year')               AS tiger_year,
           min(b.metadata->>'legislative_session_year') AS session_year,
           ST_Multi(ST_Union(b.boundary_geometry))::geometry(MultiPolygon, 4326) AS geom
      FROM spec s
      JOIN public.jurisdictions b
        ON b.parent_id = v_parent
       AND b.type = 'district'
       AND b.short_name LIKE 'HD %'
       AND b.metadata->>'chamber' = 'lower'
       AND b.metadata->>'source' = 'tiger'
       AND b.metadata->>'district_id' = ANY (s.base_district_ids)
     GROUP BY s.district_id, s.name, s.seats, s.base_district_ids
  ),
  rows_in AS (
    SELECT v_parent AS parent_id,
           'district'::jurisdiction_type AS type,
           u.name,
           'HD ' || u.district_id AS short_name,
           '33'::text AS fips_code,
           u.geom AS boundary_geometry,
           -- ST_PointOnSurface, not ST_Centroid: the project's convention for
           -- jurisdiction centroids (see 20260528170000 and 20260528180100),
           -- and the only one guaranteed to land ON an irregular or multipart
           -- polygon. The base rows' own centroids were filled the same way.
           ST_PointOnSurface(u.geom)::geometry(Point, 4326) AS centroid,
           jsonb_build_object(
             'source',                   'derived',
             'derived_from',             'tiger',
             'floterial',                true,
             'chamber',                  'lower',
             'state_abbr',               'NH',
             'state_fips',               '33',
             'district_id',              u.district_id,
             'tiger_year',               u.tiger_year,
             'legislative_session_year', u.session_year,
             'base_district_ids',        to_jsonb(u.base_district_ids),
             'statute',                  'RSA 662:5 (2022 plan)',
             'seats',                    u.seats
           ) AS metadata
      FROM unioned u
  )
  INSERT INTO public.jurisdictions (
    parent_id, type, name, short_name, country_code, fips_code, census_geoid,
    boundary_geometry, centroid, population, is_active, is_synthetic,
    coverage_status, metadata
  )
  SELECT r.parent_id, r.type, r.name, r.short_name,
         -- NULL, like every one of the 7,211 district rows that exist today.
         -- The design sketch said 'US'; the live rows say otherwise, and a
         -- district row that is the only one with a country_code would surface
         -- in listJurisdictionsByCountry() where no district appears now.
         NULL,
         r.fips_code,
         NULL,                       -- census_geoid: a floterial has no GEOID
         r.boundary_geometry, r.centroid,
         NULL,                       -- population: NULL on the base rows too
         true, false, 'none',
         r.metadata || jsonb_build_object('derived_at', to_jsonb(now()))
    FROM rows_in r
      ON CONFLICT (parent_id, (metadata->>'chamber'), (metadata->>'district_id'))
      WHERE type = 'district' AND metadata->>'source' = 'derived'
      DO UPDATE
     SET name              = EXCLUDED.name,
         short_name        = EXCLUDED.short_name,
         boundary_geometry = EXCLUDED.boundary_geometry,
         centroid          = EXCLUDED.centroid,
         metadata          = EXCLUDED.metadata,
         updated_at        = now()
   -- Only touch a row that actually changed, so a re-run over unchanged base
   -- geometry reports 0 instead of 39. derived_at is excluded from the
   -- comparison -- it is a stamp of the last real change, not a change itself.
   -- ST_AsBinary rather than IS DISTINCT FROM: the '=' operator for geometry
   -- compares BOUNDING BOXES, so a reshaped polygon with the same envelope
   -- would compare equal and the update would be skipped.
   WHERE public.jurisdictions.name       IS DISTINCT FROM EXCLUDED.name
      OR public.jurisdictions.short_name IS DISTINCT FROM EXCLUDED.short_name
      OR ST_AsBinary(public.jurisdictions.boundary_geometry)
           IS DISTINCT FROM ST_AsBinary(EXCLUDED.boundary_geometry)
      OR ST_AsBinary(public.jurisdictions.centroid)
           IS DISTINCT FROM ST_AsBinary(EXCLUDED.centroid)
      OR (public.jurisdictions.metadata - 'derived_at')
           IS DISTINCT FROM (EXCLUDED.metadata - 'derived_at');

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$fn$;

-- Route-gated by construction: only the TIGER pipeline and migrations call it.
-- Supabase default-grants EXECUTE on new functions to anon/authenticated, so
-- revoke explicitly (same posture as FIX-834).
REVOKE ALL ON FUNCTION public.derive_nh_floterials() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.derive_nh_floterials() TO service_role;

COMMENT ON FUNCTION public.derive_nh_floterials() IS
  'FIX-914 - seeds/refreshes the ${rows.length} New Hampshire floterial House districts as '
  'ST_Union of the TIGER base districts each spans, per RSA 662:5 (2022 plan). '
  'Idempotent through jurisdictions_derived_district_unique; refuses to insert a '
  'partial union. Returns rows written; a run over unchanged base geometry '
  'returns 0. Called by pipelines/districts-tiger after the SLD pass.';

-- ── Seed ────────────────────────────────────────────────────────────────────
-- In the same transaction as the definitions above, so a failure to derive
-- leaves neither the function nor a half-seeded set behind.
SELECT public.derive_nh_floterials();
`;
}

if (require.main === module) {
  const check = process.argv.includes("--check");
  const rows = readSpec();
  const next = buildMigration(rows);

  if (check) {
    const cur = fs.existsSync(MIGRATION_PATH) ? fs.readFileSync(MIGRATION_PATH, "utf8") : "";
    if (cur !== next) {
      console.error(`${path.basename(MIGRATION_PATH)} is stale — re-run without --check`);
      process.exit(1);
    }
    console.info(`${path.basename(MIGRATION_PATH)} is current`);
  } else {
    fs.writeFileSync(MIGRATION_PATH, next);
    console.info(`wrote ${path.relative(process.cwd(), MIGRATION_PATH)} — ${rows.length} floterials,` +
      ` ${rows.reduce((n, r) => n + r.seats, 0)} seats,` +
      ` ${rows.reduce((n, r) => n + r.base_district_ids.length, 0)} base-district references`);
  }
}
