-- FIX-914 — the 39 New Hampshire floterial House districts, derived as unions
-- of the TIGER base districts they span.
--
-- New Hampshire elects 400 representatives from 203 districts. 164 of those are
-- ordinary base districts and arrive as TIGER SLDL features; the other 39 are
-- FLOTERIAL districts — an overlay district spanning several WHOLE base
-- districts and electing its own representatives on top of theirs. A floterial
-- is not a Census geography, so TIGER publishes none of them, and the 58
-- representatives elected from them had no jurisdictions row to link to. That is
-- the permanent residual FIX-913 and FIX-859 documented and declined to guess at.
--
-- The membership is statutory (RSA 662:5, the 2022 plan) and is checked in at
-- packages/data/src/data/nh-house-districts-2022.json together with the proof
-- that every floterial is an EXACT union of whole base districts — no town
-- missing, none extra, no base district split. The base_district_ids below come
-- out of that proof (nh-floterials-2022.derived.json); this file is GENERATED by
-- packages/data/src/scripts/gen-fix914-migration.ts and a test asserts the two
-- agree, so the SQL cannot drift from the statute.
--
-- AFTER THIS, NEW HAMPSHIRE'S 'HD' ROWS NO LONGER PARTITION THE STATE. 39
-- polygons overlap the 164, and that is correct: a Belmont resident really is
-- represented by both Belknap 4 and Belknap 8. Readers that assumed "one
-- district contains this point" are handled in the same set as this migration;
-- see the FIX-914 reader sweep.
--
-- link_officials_to_districts() is NOT touched. Its FIX-913 body keys on
-- type='district' + an 'HD'/'SD' short_name prefix + the parent state, and
-- matches at tier 3 on the normalised core — 'Belknap 8' and 'New Hampshire
-- State House District Belknap 08' both reduce to 'belknap-08'. So a derived row
-- named in the TIGER pattern links with no RPC change and with an honest
-- metadata.source of 'derived' rather than a mislabelled 'tiger'.

-- ── Idempotency, pinned in the schema rather than in a script's memory ───────
--
-- The floterial rows carry census_geoid = NULL on purpose: a floterial is not a
-- Census geography and a fabricated '33008' would be a lie. That puts them
-- OUTSIDE jurisdictions_district_geoid_chamber_unique (which is partial on
-- census_geoid IS NOT NULL), so the derived set needs a uniqueness key of its
-- own. Without it a re-run after a TIGER refresh would mint a second Belknap 8.
CREATE UNIQUE INDEX IF NOT EXISTS jurisdictions_derived_district_unique
  ON public.jurisdictions (parent_id, (metadata->>'chamber'), (metadata->>'district_id'))
  WHERE type = 'district' AND metadata->>'source' = 'derived';

-- ── The derivation ──────────────────────────────────────────────────────────
--
-- Exposed as a function, not inlined, because the TIGER ingest calls it after
-- writing New Hampshire's lower chamber: a tiger_year bump rewrites the base
-- geometries, and the floterials must be re-unioned from the new ones or they
-- silently keep the old shape. Through the unique index above that re-union is
-- an UPDATE in place, never a second row.
--
-- statement_timeout is pinned because the pipelines call this as service_role,
-- whose prod default is 8s. 39 unions over 2-6 polygons we already hold runs in
-- seconds, but the same convention as link_officials_to_districts() applies:
-- do not leave a pipeline one slow plan away from a timeout.
CREATE OR REPLACE FUNCTION public.derive_nh_floterials()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
SET statement_timeout = '5min'
AS $fn$
DECLARE
  -- Generated from nh-floterials-2022.derived.json. district_id is the TIGER
  -- SLDLST form (county index + zero-padded number: Belknap 8 -> '008',
  -- Hillsborough 37 -> '537'); base_district_ids are the TIGER district_ids of
  -- the base districts the floterial spans -- portable across environments,
  -- never uuids.
  v_spec CONSTANT jsonb := $spec$[
  {"district_id":"008","county":"Belknap","number":8,"seats":2,"name":"New Hampshire State House District Belknap 08","base_district_ids":["003","004"]},
  {"district_id":"107","county":"Carroll","number":7,"seats":1,"name":"New Hampshire State House District Carroll 07","base_district_ids":["105","106"]},
  {"district_id":"108","county":"Carroll","number":8,"seats":2,"name":"New Hampshire State House District Carroll 08","base_district_ids":["103","104"]},
  {"district_id":"215","county":"Cheshire","number":15,"seats":2,"name":"New Hampshire State House District Cheshire 15","base_district_ids":["201","202","203","204","205","206"]},
  {"district_id":"216","county":"Cheshire","number":16,"seats":1,"name":"New Hampshire State House District Cheshire 16","base_district_ids":["207","208","209"]},
  {"district_id":"217","county":"Cheshire","number":17,"seats":1,"name":"New Hampshire State House District Cheshire 17","base_district_ids":["210","211","212"]},
  {"district_id":"218","county":"Cheshire","number":18,"seats":2,"name":"New Hampshire State House District Cheshire 18","base_district_ids":["213","214"]},
  {"district_id":"307","county":"Coos","number":7,"seats":1,"name":"New Hampshire State House District Coos 07","base_district_ids":["304","305"]},
  {"district_id":"417","county":"Grafton","number":17,"seats":1,"name":"New Hampshire State House District Grafton 17","base_district_ids":["413","414","415"]},
  {"district_id":"418","county":"Grafton","number":18,"seats":1,"name":"New Hampshire State House District Grafton 18","base_district_ids":["409","410","411","416"]},
  {"district_id":"537","county":"Hillsborough","number":37,"seats":1,"name":"New Hampshire State House District Hillsborough 37","base_district_ids":["534","543"]},
  {"district_id":"538","county":"Hillsborough","number":38,"seats":2,"name":"New Hampshire State House District Hillsborough 38","base_district_ids":["513","514"]},
  {"district_id":"539","county":"Hillsborough","number":39,"seats":2,"name":"New Hampshire State House District Hillsborough 39","base_district_ids":["515","516","520"]},
  {"district_id":"540","county":"Hillsborough","number":40,"seats":4,"name":"New Hampshire State House District Hillsborough 40","base_district_ids":["518","519","521","522","523"]},
  {"district_id":"541","county":"Hillsborough","number":41,"seats":3,"name":"New Hampshire State House District Hillsborough 41","base_district_ids":["517","524","525","526"]},
  {"district_id":"544","county":"Hillsborough","number":44,"seats":2,"name":"New Hampshire State House District Hillsborough 44","base_district_ids":["528","529"]},
  {"district_id":"545","county":"Hillsborough","number":45,"seats":1,"name":"New Hampshire State House District Hillsborough 45","base_district_ids":["535","536"]},
  {"district_id":"625","county":"Merrimack","number":25,"seats":1,"name":"New Hampshire State House District Merrimack 25","base_district_ids":["602","603"]},
  {"district_id":"626","county":"Merrimack","number":26,"seats":1,"name":"New Hampshire State House District Merrimack 26","base_district_ids":["601","604","605"]},
  {"district_id":"627","county":"Merrimack","number":27,"seats":2,"name":"New Hampshire State House District Merrimack 27","base_district_ids":["610","611","614"]},
  {"district_id":"628","county":"Merrimack","number":28,"seats":1,"name":"New Hampshire State House District Merrimack 28","base_district_ids":["615","616","617"]},
  {"district_id":"629","county":"Merrimack","number":29,"seats":1,"name":"New Hampshire State House District Merrimack 29","base_district_ids":["618","623","624"]},
  {"district_id":"630","county":"Merrimack","number":30,"seats":1,"name":"New Hampshire State House District Merrimack 30","base_district_ids":["619","620","621","622"]},
  {"district_id":"731","county":"Rockingham","number":31,"seats":2,"name":"New Hampshire State House District Rockingham 31","base_district_ids":["702","703"]},
  {"district_id":"732","county":"Rockingham","number":32,"seats":1,"name":"New Hampshire State House District Rockingham 32","base_district_ids":["706","707","708"]},
  {"district_id":"733","county":"Rockingham","number":33,"seats":1,"name":"New Hampshire State House District Rockingham 33","base_district_ids":["710","711","712"]},
  {"district_id":"734","county":"Rockingham","number":34,"seats":1,"name":"New Hampshire State House District Rockingham 34","base_district_ids":["714","715"]},
  {"district_id":"735","county":"Rockingham","number":35,"seats":1,"name":"New Hampshire State House District Rockingham 35","base_district_ids":["716","717"]},
  {"district_id":"736","county":"Rockingham","number":36,"seats":1,"name":"New Hampshire State House District Rockingham 36","base_district_ids":["719","720"]},
  {"district_id":"737","county":"Rockingham","number":37,"seats":1,"name":"New Hampshire State House District Rockingham 37","base_district_ids":["721","722"]},
  {"district_id":"738","county":"Rockingham","number":38,"seats":1,"name":"New Hampshire State House District Rockingham 38","base_district_ids":["723","724"]},
  {"district_id":"739","county":"Rockingham","number":39,"seats":1,"name":"New Hampshire State House District Rockingham 39","base_district_ids":["726","727","728"]},
  {"district_id":"740","county":"Rockingham","number":40,"seats":1,"name":"New Hampshire State House District Rockingham 40","base_district_ids":["729","730"]},
  {"district_id":"818","county":"Strafford","number":18,"seats":1,"name":"New Hampshire State House District Strafford 18","base_district_ids":["803","804"]},
  {"district_id":"819","county":"Strafford","number":19,"seats":3,"name":"New Hampshire State House District Strafford 19","base_district_ids":["805","806","807","808","809"]},
  {"district_id":"820","county":"Strafford","number":20,"seats":1,"name":"New Hampshire State House District Strafford 20","base_district_ids":["810","811"]},
  {"district_id":"821","county":"Strafford","number":21,"seats":3,"name":"New Hampshire State House District Strafford 21","base_district_ids":["813","814","815","816","817"]},
  {"district_id":"907","county":"Sullivan","number":7,"seats":1,"name":"New Hampshire State House District Sullivan 07","base_district_ids":["902","903"]},
  {"district_id":"908","county":"Sullivan","number":8,"seats":2,"name":"New Hampshire State House District Sullivan 08","base_district_ids":["904","905","906"]}
]$spec$::jsonb;
  v_parent  uuid;
  v_missing text;
  v_count   integer;
BEGIN
  SELECT id INTO v_parent
    FROM public.jurisdictions
   WHERE type = 'state' AND fips_code = '33';
  IF v_parent IS NULL THEN
    RAISE EXCEPTION 'derive_nh_floterials: no New Hampshire state jurisdiction (type=state, fips_code=33)';
  END IF;

  -- NEVER INSERT A PARTIAL UNION. A floterial that resolves fewer base rows
  -- than its list names would still produce a valid polygon -- a smaller, wrong
  -- one -- and nothing downstream would notice. Refuse the whole run instead.
  SELECT string_agg(
           format('%s (wanted %s, resolved %s)',
                  s.district_id, array_length(s.base_district_ids, 1), s.n),
           ', ' ORDER BY s.district_id)
    INTO v_missing
    FROM (
      SELECT x.district_id,
             x.base_district_ids,
             count(b.id) AS n
        FROM jsonb_to_recordset(v_spec)
               AS x(district_id text, county text, number int, seats int,
                    name text, base_district_ids text[])
        LEFT JOIN public.jurisdictions b
               ON b.parent_id = v_parent
              AND b.type = 'district'
              AND b.short_name LIKE 'HD %'
              AND b.metadata->>'chamber' = 'lower'
              AND b.metadata->>'source' = 'tiger'
              AND b.boundary_geometry IS NOT NULL
              AND b.metadata->>'district_id' = ANY (x.base_district_ids)
       GROUP BY x.district_id, x.base_district_ids
    ) s
   WHERE s.n <> array_length(s.base_district_ids, 1);

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'derive_nh_floterials: base districts missing for %', v_missing;
  END IF;

  WITH spec AS (
    SELECT * FROM jsonb_to_recordset(v_spec)
      AS x(district_id text, county text, number int, seats int,
           name text, base_district_ids text[])
  ),
  unioned AS (
    SELECT s.district_id,
           s.name,
           s.seats,
           s.base_district_ids,
           -- tiger_year and legislative_session_year are read OFF the base rows
           -- rather than frozen into this migration: after a TIGER bump the
           -- re-union must describe the geometry it actually used, not the
           -- vintage that happened to be current the day this was written.
           min(b.metadata->>'tiger_year')               AS tiger_year,
           min(b.metadata->>'legislative_session_year') AS session_year,
           ST_Multi(ST_Union(b.boundary_geometry))::geometry(MultiPolygon, 4326) AS geom
      FROM spec s
      JOIN public.jurisdictions b
        ON b.parent_id = v_parent
       AND b.type = 'district'
       AND b.short_name LIKE 'HD %'
       AND b.metadata->>'chamber' = 'lower'
       AND b.metadata->>'source' = 'tiger'
       AND b.metadata->>'district_id' = ANY (s.base_district_ids)
     GROUP BY s.district_id, s.name, s.seats, s.base_district_ids
  ),
  rows_in AS (
    SELECT v_parent AS parent_id,
           'district'::jurisdiction_type AS type,
           u.name,
           'HD ' || u.district_id AS short_name,
           '33'::text AS fips_code,
           u.geom AS boundary_geometry,
           -- ST_PointOnSurface, not ST_Centroid: the project's convention for
           -- jurisdiction centroids (see 20260528170000 and 20260528180100),
           -- and the only one guaranteed to land ON an irregular or multipart
           -- polygon. The base rows' own centroids were filled the same way.
           ST_PointOnSurface(u.geom)::geometry(Point, 4326) AS centroid,
           jsonb_build_object(
             'source',                   'derived',
             'derived_from',             'tiger',
             'floterial',                true,
             'chamber',                  'lower',
             'state_abbr',               'NH',
             'state_fips',               '33',
             'district_id',              u.district_id,
             'tiger_year',               u.tiger_year,
             'legislative_session_year', u.session_year,
             'base_district_ids',        to_jsonb(u.base_district_ids),
             'statute',                  'RSA 662:5 (2022 plan)',
             'seats',                    u.seats
           ) AS metadata
      FROM unioned u
  )
  INSERT INTO public.jurisdictions (
    parent_id, type, name, short_name, country_code, fips_code, census_geoid,
    boundary_geometry, centroid, population, is_active, is_synthetic,
    coverage_status, metadata
  )
  SELECT r.parent_id, r.type, r.name, r.short_name,
         -- NULL, like every one of the 7,211 district rows that exist today.
         -- The design sketch said 'US'; the live rows say otherwise, and a
         -- district row that is the only one with a country_code would surface
         -- in listJurisdictionsByCountry() where no district appears now.
         NULL,
         r.fips_code,
         NULL,                       -- census_geoid: a floterial has no GEOID
         r.boundary_geometry, r.centroid,
         NULL,                       -- population: NULL on the base rows too
         true, false, 'none',
         r.metadata || jsonb_build_object('derived_at', to_jsonb(now()))
    FROM rows_in r
      ON CONFLICT (parent_id, (metadata->>'chamber'), (metadata->>'district_id'))
      WHERE type = 'district' AND metadata->>'source' = 'derived'
      DO UPDATE
     SET name              = EXCLUDED.name,
         short_name        = EXCLUDED.short_name,
         boundary_geometry = EXCLUDED.boundary_geometry,
         centroid          = EXCLUDED.centroid,
         metadata          = EXCLUDED.metadata,
         updated_at        = now()
   -- Only touch a row that actually changed, so a re-run over unchanged base
   -- geometry reports 0 instead of 39. derived_at is excluded from the
   -- comparison -- it is a stamp of the last real change, not a change itself.
   -- ST_AsBinary rather than IS DISTINCT FROM: the '=' operator for geometry
   -- compares BOUNDING BOXES, so a reshaped polygon with the same envelope
   -- would compare equal and the update would be skipped.
   WHERE public.jurisdictions.name       IS DISTINCT FROM EXCLUDED.name
      OR public.jurisdictions.short_name IS DISTINCT FROM EXCLUDED.short_name
      OR ST_AsBinary(public.jurisdictions.boundary_geometry)
           IS DISTINCT FROM ST_AsBinary(EXCLUDED.boundary_geometry)
      OR ST_AsBinary(public.jurisdictions.centroid)
           IS DISTINCT FROM ST_AsBinary(EXCLUDED.centroid)
      OR (public.jurisdictions.metadata - 'derived_at')
           IS DISTINCT FROM (EXCLUDED.metadata - 'derived_at');

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$fn$;

-- Route-gated by construction: only the TIGER pipeline and migrations call it.
-- Supabase default-grants EXECUTE on new functions to anon/authenticated, so
-- revoke explicitly (same posture as FIX-834).
REVOKE ALL ON FUNCTION public.derive_nh_floterials() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.derive_nh_floterials() TO service_role;

COMMENT ON FUNCTION public.derive_nh_floterials() IS
  'FIX-914 - seeds/refreshes the 39 New Hampshire floterial House districts as '
  'ST_Union of the TIGER base districts each spans, per RSA 662:5 (2022 plan). '
  'Idempotent through jurisdictions_derived_district_unique; refuses to insert a '
  'partial union. Returns rows written; a run over unchanged base geometry '
  'returns 0. Called by pipelines/districts-tiger after the SLD pass.';

-- ── Seed ────────────────────────────────────────────────────────────────────
-- In the same transaction as the definitions above, so a failure to derive
-- leaves neither the function nor a half-seeded set behind.
SELECT public.derive_nh_floterials();
