"use client";

/**
 * AiSummarySection
 *
 * Used on the proposal detail page when no cached summary is available
 * at render time. Fetches on mount, shows a loading state, then reveals
 * the generated summary. Result is cached server-side on first call —
 * subsequent visitors get it instantly.
 */

import { useEffect, useState } from "react";

type Props = {
  proposalId: string;
};

export function AiSummarySection({ proposalId }: Props) {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    fetch(`/api/proposals/${proposalId}/summary`)
      .then((r) => r.json())
      .then((data: { summary: string | null }) => {
        if (!cancelled) {
          setSummary(data.summary ?? null);
          setLoading(false);
        }
      })
      .catch(() => {
        if (!cancelled) setLoading(false);
      });

    return () => { cancelled = true; };
  }, [proposalId]);

  if (loading) {
    return (
      <section>
        <h2 className="mb-3 font-mono text-xs font-semibold uppercase tracking-wide text-ink-soft/70">
          What This Means
        </h2>
        <div className="border border-civic-blue/20 bg-civic-blue/5 p-5">
          <div className="flex items-center gap-2 text-sm text-ink-soft">
            <span className="inline-block h-3 w-3 animate-spin rounded-full border-2 border-rule border-t-accent" />
            Generating plain language summary…
          </div>
        </div>
      </section>
    );
  }

  if (!summary) return null;

  return (
    <section>
      <h2 className="mb-3 font-mono text-xs font-semibold uppercase tracking-wide text-ink-soft/70">
        What This Means
      </h2>
      <div className="border border-civic-blue/20 bg-card p-5">
        <p className="text-sm text-ink leading-relaxed">{summary}</p>
        <p className="mt-3 font-mono text-[10px] uppercase tracking-[0.08em] text-ink-soft/70">
          Plain language summary generated by AI · Civitics
        </p>
      </div>
    </section>
  );
}
